services:
  gym_tracker_bot:
    build: .
    container_name: gym_tracker_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./bot.log:/app/bot.log
